name: Terraform

on:
  push:
    branches:
      - "**"   
jobs:
  terraform_plan:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  
      contents: read    

    env:
      TF_IN_AUTOMATION: true
      TF_CLI_ARGS: "-input=false"

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Authenticate with AWS using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ vars.OIDC_AWS_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.1

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false
        
  terraform_deploy:
    runs-on: ubuntu-latest
    needs: terraform_plan
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve
        
