name: Terraform Apply

on:
  push:
    branches:
      - "**"   
jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  
      contents: read    

    env:
      TF_IN_AUTOMATION: true
      TF_CLI_ARGS: "-input=false"

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Authenticate with AWS using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::YOUR-AWS-ACCOUNT-ID:role/YOUR-ROLE-NAME
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Cache Terraform modules and plugins
        uses: actions/cache@v3
        with:
          path: |
            ~/.terraform.d/plugin-cache
            .terraform
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve
        env:
          TF_VAR_access_key: ${{ secrets.TF_VAR_access_key }}
          TF_VAR_secret_key: ${{ secrets.TF_VAR_secret_key }}
