name: Terraform

on:
  push:
    branches:
      - "**"   
jobs:
  terraform_plan:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  
      contents: read    

    env:
      TF_IN_AUTOMATION: true
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Authenticate with AWS using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ vars.OIDC_AWS_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.1

      - name: terraform validate
        uses: dflook/terraform-validate@v1
        with:
          path: terraform
        
  terraform_deploy:
    needs: terraform_plan
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: terraform
          auto_approve: true
        
