name: Terraform

on:
  push:
    branches:
      - "**"   
jobs:
  terraform_pre_apply:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  
      contents: read    

    env:
      TF_IN_AUTOMATION: true
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Authenticate with AWS using OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ vars.OIDC_AWS_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}


      - name: terraform plan
        uses: "infinite-automations/terraform-all-in-one@v1.2.0"
        with:
          directory: "terraform"
          apply: false
          setup: true
          init: true
          format: false
          validate: true
          plan: true
          

      - name: terraform apply
        uses: "infinite-automations/terraform-all-in-one@v1.2.0"
        if: github.ref == 'refs/heads/main'
        with:
          directory: "terraform"
          apply: true
          apply-args: "-auto-approve"
          setup: true
          init: true
          format: false
          validate: true
          plan: false
